#!/bin/bash

(
MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$MY_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi
export IRONPYTHONPATH="$IRONPYTHONPATH;$LITS3_PATH;$MY_PATH/Release;$MY_PATH/Debug;$MY_PATH/../LitS3/bin/Release;$MY_PATH/../LitS3/bin/Debug"
mono $MY_PATH/ipy/ipy.exe $MY_PATH/s3cmd.py "$@"
)
